<?php
return array (
  'account' => 
  array (
    'fieldid' => '150',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'account',
    'name' => '昵 称',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'mtype' => '9',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '1',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'sex' => 
  array (
    'fieldid' => '151',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'sex',
    'name' => '性别',
    'tips' => '性别',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'男|1
女|0\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '男|1
女|0',
    'boxtype' => 'radio',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '1',
  ),
  'birthday' => 
  array (
    'fieldid' => '83',
    'modelid' => '10',
    'siteid' => '1',
    'field' => 'birthday',
    'name' => '生日',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '生日格式错误',
    'formtype' => 'datetime',
    'mtype' => '8',
    'setting' => 'array (
  \'fieldtype\' => \'date\',
  \'format\' => \'Y-m-d\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'fieldtype' => 'date',
    'format' => 'Y-m-d',
    'defaulttype' => '0',
  ),
  'mobile' => 
  array (
    'fieldid' => '152',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'mobile',
    'name' => '手机号码',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'mtype' => '8',
    'setting' => 'array (
  \'size\' => \'15\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '3',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'size' => '15',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'marriage' => 
  array (
    'fieldid' => '153',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'marriage',
    'name' => '婚姻状况',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'已婚|1
离异|2
未婚|3
丧偶|4\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'smallint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '已婚|1
离异|2
未婚|3
丧偶|4',
    'boxtype' => 'select',
    'fieldtype' => 'smallint',
    'minnumber' => '-1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
  'children' => 
  array (
    'fieldid' => '154',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'children',
    'name' => '子女',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'无|0
1个|1
2个|2
3个|3
4个|4
4个以上|5\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '5',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '无|0
1个|1
2个|2
3个|3
4个|4
4个以上|5',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '0',
  ),
  'education' => 
  array (
    'fieldid' => '155',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'education',
    'name' => '学历',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'小学|1
高中|2
中专|3
专科|4
本科|5
研究生|6
硕士|7
博士|8
博士后|9
其他|10\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '6',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '小学|1
高中|2
中专|3
专科|4
本科|5
研究生|6
硕士|7
博士|8
博士后|9
其他|10',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
  'income' => 
  array (
    'fieldid' => '156',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'income',
    'name' => '月收入',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'1000元以下|1
1001-2000|2
2001-3000|3
3001-4000|4
4001-5000|5
5001-8000|6
8001-10000|7
10001-30000|8
30001-50000|9
50000以上|10\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'-1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '7',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '1000元以下|1
1001-2000|2
2001-3000|3
3001-4000|4
4001-5000|5
5001-8000|6
8001-10000|7
10001-30000|8
30001-50000|9
50000以上|10',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '-1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '0',
  ),
  'social' => 
  array (
    'fieldid' => '157',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'social',
    'name' => '社保',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'有|1
没有|0
\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '8',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '有|1
没有|0
',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
  'social_num' => 
  array (
    'fieldid' => '158',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'social_num',
    'name' => '社保电脑号',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'mtype' => '8',
    'setting' => 'array (
  \'size\' => \'15\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '9',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'size' => '15',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'house_condition' => 
  array (
    'fieldid' => '159',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'house_condition',
    'name' => '住房条件',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'租房|0
自由租房|1
其它|2\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '租房|0
自由租房|1
其它|2',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '0',
  ),
  'buy_car' => 
  array (
    'fieldid' => '160',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'buy_car',
    'name' => '是否购车',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'mtype' => '8',
    'setting' => 'array (
  \'options\' => \'有|1
无|0
\',
  \'boxtype\' => \'select\',
  \'fieldtype\' => \'tinyint\',
  \'minnumber\' => \'1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'1\',
  \'outputtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'isaddReg' => '0',
    'options' => '有|1
无|0
',
    'boxtype' => 'select',
    'fieldtype' => 'tinyint',
    'minnumber' => '1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '0',
  ),
);
?>