<?php
return array (
  23 => 
  array (
    'catid' => '23',
    'siteid' => '1',
    'type' => '2',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '',
    'child' => '0',
    'arrchildid' => '',
    'catname' => '我要投资',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://phpcms.dev?m=invest&c=index',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => '',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => NULL,
    'ishtml' => NULL,
    'content_ishtml' => NULL,
    'category_ruleid' => NULL,
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  24 => 
  array (
    'catid' => '24',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '23',
    'arrparentid' => '0,23',
    'child' => '0',
    'arrchildid' => '24',
    'catname' => '借款标的类型说明',
    'style' => '',
    'image' => '',
    'description' => '借款标的类型说明',
    'parentdir' => '/',
    'catdir' => 'invest_type',
    'url' => 'http://phpcms.dev/index.php?m=content&c=index&a=lists&catid=24',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'rfw88\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '24',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jiekuanbiaodeleixingshuoming',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  25 => 
  array (
    'catid' => '25',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '25',
    'catname' => '我要贷款',
    'style' => '',
    'image' => '',
    'description' => '我要贷款',
    'parentdir' => '',
    'catdir' => 'borrow',
    'url' => 'http://phpcms.dev/index.php?m=content&c=index&a=lists&catid=25',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'rfw88\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '25',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'woyaodaikuan',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>