<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '融富网主站',
    'dirname' => '',
    'domain' => 'http://phpcms.dev/',
    'site_title' => '融富网',
    'keywords' => '融富网',
    'description' => '融富网',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => 'array (
  \'upload_maxsize\' => \'2048\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'1\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water//mark.png\',
  \'watermark_pct\' => \'85\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => 'e2d1b156-e6b4-11e2-a3c6-c8524254e16b',
    'url' => 'http://phpcms.dev/',
  ),
  2 => 
  array (
    'siteid' => '2',
    'name' => '北京',
    'dirname' => 'bj',
    'domain' => 'http://bj.phpcms.dev/',
    'site_title' => '北京融富网',
    'keywords' => '北京融富网',
    'description' => '北京融富网',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => 'array (
  \'upload_maxsize\' => \'2000\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'1\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water/http://phpcms.dev/mark.gif\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '',
    'url' => 'http://bj.phpcms.dev/',
  ),
  3 => 
  array (
    'siteid' => '3',
    'name' => '深圳',
    'dirname' => 'sz',
    'domain' => 'http://sz.phpcms.dev/',
    'site_title' => '深圳融富网',
    'keywords' => '深圳融富网',
    'description' => '深圳融富网',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => 'array (
  \'upload_maxsize\' => \'2000\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'1\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'http://phpcms.dev/statics/images/water/mark.gif\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '',
    'url' => 'http://sz.phpcms.dev/',
  ),
);
?>